-- This file is for use with Corona(R) SDK
--
-- This file is automatically generated with PhysicsEdtior (http://physicseditor.de). Do not edit
--
-- Usage example:
--			local scaleFactor = 1.0
--			local physicsData = (require "shapedefs").physicsData(scaleFactor)
--			local shape = display.newImage("objectname.png")
--			physics.addBody( shape, physicsData:get("objectname") )
--

-- copy needed functions to local scope
local unpack = unpack
local pairs = pairs
local ipairs = ipairs

local M = {}

function M.physicsData(scale)
	local physics = { data =
	{ 
		
		["spin&amp;match"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "blue", density = 2, friction = 0, bounce = 1.01, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -246, 86  ,  -104, 228  ,  -110, 234  ,  -252, 92  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "yellow", density = 2, friction = 0, bounce = 1.01, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -111, -233  ,  -105, -227  ,  -246, -86  ,  -252, -92  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "aqua", density = 2, friction = 0, bounce = 1.01, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   111, -234  ,  252, -93  ,  245, -86  ,  104, -227  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "red", density = 2, friction = 0, bounce = 1.01, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   252, 93  ,  111, 233  ,  105, 227  ,  245, 86  }
                    }
                    
                    
                    
		}
		
	} }

        -- apply scale factor
        local s = scale or 1.0
        for bi,body in pairs(physics.data) do
                for fi,fixture in ipairs(body) do
                    if(fixture.shape) then
                        for ci,coordinate in ipairs(fixture.shape) do
                            fixture.shape[ci] = s * coordinate
                        end
                    else
                        fixture.radius = s * fixture.radius
                    end
                end
        end
	
	function physics:get(name)
		return unpack(self.data["spin&amp;match"])
	end

	function physics:getFixtureId(name, index)
                return self.data["spin&amp;match"][index].pe_fixture_id
	end
	
	return physics;
end

return M

